version: '3.7'
services:
  postgres:
    image: postgres:12.2
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: slaids_db
    ports:
      - 5432:5432
